//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystemV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbLeadManagementSystemV2Entities : DbContext
    {
        public DbLeadManagementSystemV2Entities()
            : base("name=DbLeadManagementSystemV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MenuPermission> MenuPermissions { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<LatestNewsGalleryLink> LatestNewsGalleryLinks { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<GalleryDetail> GalleryDetails { get; set; }
        public virtual DbSet<LatestNew> LatestNews { get; set; }
        public virtual DbSet<NewsLetter> NewsLetters { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<QuestionDetail> QuestionDetails { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<BusinessApplication> BusinessApplications { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<OrgAnnouncement> OrgAnnouncements { get; set; }
        public virtual DbSet<OrgAnnouncementDetail> OrgAnnouncementDetails { get; set; }
    }
}
