//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystemV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryDetail
    {
        public int ID { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual Gallery Gallery { get; set; }
    }
}
