//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystemV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgAnnouncementDetail
    {
        public int ID { get; set; }
        public int OrgAnnoucmentID { get; set; }
        public string Files { get; set; }
    
        public virtual OrgAnnouncement OrgAnnouncement { get; set; }
    }
}
