//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystemV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionDetail
    {
        public int ID { get; set; }
        public Nullable<int> QuestionsId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
