//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystemV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServeyResponseMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServeyResponseMaster()
        {
            this.ServeyResponseAnswers = new HashSet<ServeyResponseAnswer>();
        }
    
        public int ID { get; set; }
        public int ServeyMasterId { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual ServeyMaster ServeyMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServeyResponseAnswer> ServeyResponseAnswers { get; set; }
    }
}
