//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystemV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServeyResponseAnswer
    {
        public int ID { get; set; }
        public int ServeyResponseMasterId { get; set; }
        public int QuestionId { get; set; }
        public string Response { get; set; }
    
        public virtual ServeyQuestion ServeyQuestion { get; set; }
        public virtual ServeyResponseMaster ServeyResponseMaster { get; set; }
    }
}
